### ISSUE TITLE
synctool --check-update is now broken

### ISSUE THREAD

**Issue by walterdejong** [walterdejong/synctool#45]
I moved the website to github pages. Consequently, `synctool --check-update` broke:
```
synctool --check-update
Traceback (most recent call last):
  File "/opt/synctool/sbin/synctool_master.py", line 19, in <module>
    synctool.main.master.main()
  File "/opt/synctool/lib/synctool/main/wrapper.py", line 26, in wrap
    ret = func(*args, **kwargs)
  File "/opt/synctool/lib/synctool/main/master.py", line 714, in main
    if not synctool.update.check():
  File "/opt/synctool/lib/synctool/update.py", line 83, in check
    latest_version = get_latest_version()
  File "/opt/synctool/lib/synctool/update.py", line 29, in get_latest_version
    tup = get_latest_version_and_checksum()
  File "/opt/synctool/lib/synctool/update.py", line 47, in get_latest_version_and_checksum
    error('webserver at %s: %s' % (VERSION_CHECKING_URL, err.reason))
AttributeError: 'HTTPError' object has no attribute 'reason'
```

And it doesn't print the error message nicely ...

Same thing applies to `synctool --download`.

**Comment by walterdejong** [comment]
Error message is fixed. But the functionality is still broken because `LATEST.txt` is missing on the server.
Maybe this could be put into branch `gh-pages` (?)

**Comment by walterdejong** [comment]
`LATEST.txt` has been put into branch `gh-pages`.
A permanent redirect to github was put into the webserver so that current versions can download version 6.2.

Newer versions include URLs to github, and they use https.
Newer versions use a sha512 checksum rather than md5 (backwards compatibility works with md5)
